# Generated by Django 3.0.6 on 2020-05-07 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200507_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='reporter',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
