# Generated by Django 3.0.6 on 2020-05-07 10:40

from django.db import migrations, models
import django.db.models.deletion
import stocks.models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200507_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='unknown', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NaturalIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_flat', models.DecimalField(decimal_places=15, max_digits=30)),
                ('price_currency', models.CharField(choices=[(stocks.models.Currencies['USD'], 'USD'), (stocks.models.Currencies['EUR'], 'EUR'), (stocks.models.Currencies['PLN'], 'PLN')], max_length=30)),
                ('price_unit', models.CharField(choices=[(stocks.models.Units['KG'], 'KG'), (stocks.models.Units['LB'], 'LB'), (stocks.models.Units['MT'], 'MT'), (stocks.models.Units['LT'], 'LT')], max_length=30)),
                ('price_per_unit', models.DecimalField(decimal_places=15, max_digits=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_shelf_life_months',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=30)),
                ('natural_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.NaturalIngredients')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=30)),
                ('sold', models.BooleanField(null=True)),
                ('provider_type', models.CharField(choices=[(stocks.models.ProviderType['PROD'], 'Producer'), (stocks.models.ProviderType['SUPP'], 'Supplier'), (stocks.models.ProviderType['PROD_SUPP'], 'Producer and Supplier')], max_length=30)),
                ('contact_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('categoryType', models.CharField(choices=[(stocks.models.Categories['PROTEIN'], 'Protein'), (stocks.models.Categories['MILK_SUBSTITUTE'], 'Milk Substitute'), (stocks.models.Categories['PASTE'], 'Paste'), (stocks.models.Categories['SWEETENER'], 'Sweetener'), (stocks.models.Categories['OIL'], 'Oil'), (stocks.models.Categories['FRUIT'], 'Fruit')], max_length=30)),
                ('protein_content', models.CharField(max_length=30, null=True)),
                ('production_type', models.CharField(max_length=30, null=True)),
                ('fat_content', models.CharField(max_length=30, null=True)),
                ('additives', models.CharField(max_length=30, null=True)),
                ('soluble', models.BooleanField(null=True)),
                ('liquid', models.BooleanField(null=True)),
                ('powder', models.BooleanField(null=True)),
                ('roasted', models.BooleanField(null=True)),
                ('fineness', models.CharField(max_length=30, null=True)),
                ('natural', models.BooleanField(null=True)),
                ('process_type', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Source')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Country'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Price'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='provider_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Provider'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='source_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Source'),
        ),
    ]
