# Generated by Django 3.0.6 on 2020-05-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20200507_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.Category'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.Country'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.Country'),
        ),
    ]
