# Generated by Django 3.0.6 on 2020-05-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20200507_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock'),
        ),
    ]
