# Generated by Django 3.0.6 on 2020-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20200507_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='prices',
            field=models.ManyToManyField(to='stocks.Price'),
        ),
        migrations.DeleteModel(
            name='IngredientPrice',
        ),
    ]
